INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Cheese Burger', FALSE);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Ham Burger', FALSE);
INSERT INTO BURGERS (BURGER_NAME, DEVOURED) VALUES ('Chicken Burger', FALSE);